spring:
    data:
        elasticsearch:
            client:
                reactive:
                    endpoints: 106.13.23.17:9200
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.41.59.128:3306/Blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 7CA3133452d2
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 10
            max-active: 30
            min-idle: 1
            max-wait: 3000
            max-open-prepared-statements: -1
            time-between-eviction-runs-millis: 60000
                #      配置连接在池中的最小生存时间
            min-evictable-idle-time-millis: 300000
            #      配置连接在池中的最大生存时间
            max-evictable-idle-time-millis: 400000
            #      系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
            validation-query: SELECT 1
            #      启用空闲连接检测，以便回收
            test-while-idle: true
            #      从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
            test-on-borrow: false
            #      释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
            test-on-return: false
            #      打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: 20
            #      配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,wall
            use-global-data-source-stat: true
            #      通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    redis:
        database: 0
        # 连接超时时间（毫秒）
        timeout: 1000
        lettuce:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 10
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0
        sentinel:
            master: mymaster
            nodes: 121.41.59.128:6382,121.41.59.128:6383,121.41.59.128:6384
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB

minio:
    endPoint: http://106.13.23.17:9000
    accessKey: minioadmin
    secretKey: minioadmin