spring:
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        username: root
        password: root
        url: jdbc:p6spy:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    redis:
        host: localhost
        port: 6379
        database: 0
        password:
        # 连接超时时间（毫秒）
        timeout: 1000
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 10
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0

