server:
    port: 15000
spring:
    application:
        name: blog-core
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 114.132.227.186:8848
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
        local-cache-scope: session
        cache-enabled: true
logging:
    pattern:
        dateformat: yyyy-MM-dd HH:mm:ss
